# Generated by Django 3.2.3 on 2021-08-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhardocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='buspassdocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='dldocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pancarddocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='passportdocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='rationcarddocument',
            name='username',
        ),
        migrations.RemoveField(
            model_name='voteriddocument',
            name='username',
        ),
    ]
